### ISSUE TITLE
Make use of testcontainers instead of docker-compose files

### ISSUE THREAD

**Issue by Tochemey** [chmodas/akka-persistence-r2dbc#107]
At the moment to run test I can see we make use of some docker compose files. It is not bad but it is not scalable.

I will be adding some [testcontainers](https://github.com/testcontainers/testcontainers-scala) for the tests.

**Comment by chmodas** [comment]
I don't understand what you mean by "it is not scalable". Could you please elaborate? 

In any case, you should know that I am not too keen on replacing Compose with test containers and would require quite a bit of convincing:

1. Docker Compose is ubiquitous and language agnostic; great for those who jump between different stacks. While I've used `testcontainers` in the past, I don't believe it adds any real value.
2.  When Docker introduced backward-incompatible changes to the types in their API, testcontainers' fix arrived rather slowly. I've bumped into similar issues twice or thrice before I gave up on it
3. While not too important, Docker Compose and Docker's release cycles are not far apart, thus you can use new feature when they are introduce.

**Comment by Tochemey** [comment]
Ok that is cool
